### ISSUE TITLE
Support for mss570

### ISSUE THREAD

**Issue by zpeters90** [donavanbecker/homebridge-meross-cloud#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donavanbecker** [comment]
@zpeters90 not sure if you have saw or not, I was able to publish version 1.0.1. This version only supports mss110 right now but I would like to get this Meross device supported also. I have changed the device discovery up a little and was wondering if you could install the latest version of homebridge-meross-cloud? login and turn on devicediscovery?

then you would reboot homebridge and grab the new logs that will be outputted from this device discovery and paste them here so I can see what kind of command I can send to this device. Thanks!

**Comment by zpeters90** [comment]
Hey Donavan, I’m so sorry I missed this! Family stuff has had me not paying any attention. I just installed the new version, and turned on device discovery, rebooted, and here are the logs. I’m sorry that I’m a novice, are the logs what show up in the terminal?

**Comment by zpeters90** [comment]
3/15/2021, 8:02:11 PM HOOBS listening on port 80.
3/15/2021, 8:02:13 PM Initializing HAP-NodeJS v0.9.3...
3/15/2021, 8:02:15 PM [3/15/2021, 6:02:14 PM] The plugin "homebridge-meross" requires Node.js version of >=14.16.0 which does not satisfy the current Node.js version of v12.19.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
3/15/2021, 8:02:15 PM Loaded plugin 'homebridge-meross'
3/15/2021, 8:02:15 PM [3/15/2021, 6:02:15 PM] Registering platform 'homebridge-meross.Meross'
3/15/2021, 8:02:15 PM [3/15/2021, 6:02:15 PM] The plugin "homebridge-meross-cloud" requires Node.js version of >=14.16.0 which does not satisfy the current Node.js version of v12.19.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
3/15/2021, 8:02:17 PM Loaded plugin 'homebridge-meross-cloud'
3/15/2021, 8:02:17 PM [3/15/2021, 6:02:17 PM] Registering platform 'homebridge-meross-cloud.MerossCloud'
3/15/2021, 8:02:17 PM Loaded plugin 'homebridge-myq'

**Comment by zpeters90** [comment]
3/15/2021, 8:55:46 PM HOOBS listening on port 80.
3/15/2021, 8:56:01 PM Initializing HAP-NodeJS v0.9.3...
3/15/2021, 8:56:04 PM [3/15/2021, 6:56:04 PM] The plugin "homebridge-meross-cloud" requires Node.js version of >=14.16.0 which does not satisfy the current Node.js version of v12.19.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
3/15/2021, 8:56:07 PM Loaded plugin 'homebridge-meross-cloud'
3/15/2021, 8:56:07 PM [3/15/2021, 6:56:07 PM] Registering platform 'homebridge-meross-cloud.MerossCloud'
3/15/2021, 8:56:07 PM Loaded plugin 'homebridge-myq'
3/15/2021, 8:56:07 PM [3/15/2021, 6:56:07 PM] Registering platform 'homebridge-myq.myQ'
3/15/2021, 8:56:10 PM Loaded plugin 'homebridge-ring'
3/15/2021, 8:56:10 PM Loading 3 platforms...
3/15/2021, 8:56:10 PM [3/15/2021, 6:56:10 PM] Registering platform 'homebridge-ring.Ring'
3/15/2021, 8:56:10 PM [Ring] Initializing Ring platform...
3/15/2021, 8:56:10 PM [myQ] Initializing myQ platform...
3/15/2021, 8:56:10 PM [MerossCloud] Initializing MerossCloud platform...
3/15/2021, 8:56:10 PM [MerossCloud] Using Default Refresh Rate.
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory aefe75bc-3f6d-400e-a175-b66a3145644c Ring Alarm
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory e70bf25a-2b8d-45e6-a2a4-34d7afdb6703 Back Door
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory 2e84dfb5-72ac-4f38-8216-81b5e35cc0c0 Front Door
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory 35cf32a0-7cce-40b7-b4d4-4e77a2bf5d73 Front Door
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory 173b3f96-4602-4f26-afb2-610c4ff58302 Side Door
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory 71ff8704-fc4a-4af8-ac20-7f02f0a4278f Front Door
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory a4827bbb-a607-44f0-b4b9-24b762710dbc Garage
3/15/2021, 8:56:10 PM [Ring] Configuring cached accessory aefe75bc-3f6d-400e-a175-b66a3145644c Alarm
3/15/2021, 8:56:10 PM Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: aefe75bc-3f6d-400e-a175-b66a3145644c
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by zpeters90** [comment]
3/15/2021, 9:23:26 PM HOOBS listening on port 80.
3/15/2021, 9:23:28 PM Initializing HAP-NodeJS v0.9.3...
3/15/2021, 9:23:30 PM [3/15/2021, 7:23:30 PM] The plugin "homebridge-meross-cloud" requires Node.js version of >=14.16.0 which does not satisfy the current Node.js version of v12.19.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
3/15/2021, 9:23:32 PM Loaded plugin 'homebridge-meross-cloud'
3/15/2021, 9:23:32 PM [3/15/2021, 7:23:32 PM] Registering platform 'homebridge-meross-cloud.MerossCloud'
3/15/2021, 9:23:33 PM Loaded plugin 'homebridge-myq'
3/15/2021, 9:23:33 PM [3/15/2021, 7:23:33 PM] Registering platform 'homebridge-myq.myQ'
3/15/2021, 9:23:35 PM Loaded plugin 'homebridge-ring'
3/15/2021, 9:23:35 PM Loading 3 platforms...
3/15/2021, 9:23:35 PM [3/15/2021, 7:23:35 PM] Registering platform 'homebridge-ring.Ring'
3/15/2021, 9:23:35 PM [Ring] Initializing Ring platform...
3/15/2021, 9:23:35 PM [myQ] Initializing myQ platform...
3/15/2021, 9:23:35 PM [MerossCloud] Initializing MerossCloud platform...
3/15/2021, 9:23:35 PM [MerossCloud] Using Default Refresh Rate.
3/15/2021, 9:23:35 PM [Ring] Configuring cached accessory aefe75bc-3f6d-400e-a175-b66a3145644c Alarm
3/15/2021, 9:23:35 PM [Ring] Configuring cached accessory e70bf25a-2b8d-45e6-a2a4-34d7afdb6703 Back Door
3/15/2021, 9:23:35 PM [Ring] Configuring cached accessory 2e84dfb5-72ac-4f38-8216-81b5e35cc0c0 Front Door
3/15/2021, 9:23:35 PM [Ring] Configuring cached accessory 35cf32a0-7cce-40b7-b4d4-4e77a2bf5d73 Front Door
3/15/2021, 9:23:35 PM [Ring] Configuring cached accessory 173b3f96-4602-4f26-afb2-610c4ff58302 Side Door
3/15/2021, 9:23:35 PM [Ring] Configuring cached accessory 71ff8704-fc4a-4af8-ac20-7f02f0a4278f Front Door
3/15/2021, 9:23:35 PM [Ring] Configuring cached accessory a4827bbb-a607-44f0-b4b9-24b762710dbc Garage
3/15/2021, 9:23:35 PM Preparing Advertiser for 'HOOBS 54E8' using bonjour-hap backend!
3/15/2021, 9:23:35 PM Starting to advertise 'HOOBS 54E8' using bonjour-hap backend!
3/15/2021, 9:23:35 PM Bridge is running on port 51826.
3/15/2021, 9:23:36 PM [MerossCloud] Device Type: mss570x, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC
3/15/2021, 9:23:36 PM [MerossCloud] All-Data: {"all":{"system":{"hardware":{"type":"mss570x","subType":"us","version":"3.0.0","chipType":"mt7682","uuid":"2008144197594825582748e1e92b1b53","macAddress":"48:e1:e9:2b:1b:53"},"firmware":{"version":"3.1.2","compileTime":"2020/05/20 15:35:35 GMT +08:00","wifiMac":"10:93:97:68:c1:40","innerIp":"192.168.1.187","server":"mqtt.meross.com","port":443,"userId":906734},"time":{"timestamp":1615857827,"timezone":"America/New_York","timeRule":[[1604210400,-18000,0],[1615705200,-14400,1],[1636264800,-18000,0],[1647154800,-14400,1],[1667714400,-18000,0],[1678604400,-14400,1],[1699164000,-18000,0],[1710054000,-14400,1],[1730613600,-18000,0],[1741503600,-14400,1],[1762063200,-18000,0],[1772953200,-14400,1],[1793512800,-18000,0],[1805007600,-14400,1],[1825567200,-18000,0],[1836457200,-14400,1],[1857016800,-18000,0],[1867906800,-14400,1],[1888466400,-18000,0],[1899356400,-14400,1]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":1615847147}],"triggerx":[],"timerx":[],"light":{"capacity":4,"channel":0,"luminance":75}}}}
3/15/2021, 9:23:36 PM [MerossCloud] System-Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"Appliance.Config.Calibration":{},"Appliance.System.All":{},"Appliance.System.Hardware":{},"Appliance.System.Firmware":{},"Appliance.System.Debug":{},"Appliance.System.Online":{},"Appliance.System.Time":{},"Appliance.System.Clock":{},"Appliance.System.Ability":{},"Appliance.System.Runtime":{},"Appliance.System.Report":{},"Appliance.System.Position":{},"Appliance.System.DNDMode":{},"Appliance.Control.Multiple":{"maxCmdNum":5},"Appliance.Control.ToggleX":{},"Appliance.Control.TimerX":{"sunOffsetSupport":1},"Appliance.Control.TriggerX":{},"Appliance.Control.Bind":{},"Appliance.Control.Unbind":{},"Appliance.Control.Upgrade":{},"Appliance.Control.Light":{"capacity":4},"Appliance.Digest.TriggerX":{},"Appliance.Digest.TimerX":{}}}
3/15/2021, 9:23:36 PM [Ring] Found the following locations:
3/15/2021, 9:23:36 PM [Ring]   locationId: 19a328e9-2211-43d2-813b-b0eaff3202ed - Columbus
3/15/2021, 9:23:36 PM [Ring] Creating location socket.io connection - Columbus
3/15/2021, 9:23:37 PM [Ring] Ring connected to socket.io server
3/15/2021, 9:23:37 PM [Ring] Configuring 2 cameras and 15 devices for location "Columbus" - locationId: 19a328e9-2211-43d2-813b-b0eaff3202ed
3/15/2021, 9:23:37 PM [Ring] Hidden accessory 6f34bf48-2aec-4b53-bfad-1655e4385fde adapter.sidewalk Sidewalk Adapter
3/15/2021, 9:23:37 PM [Ring] Hidden accessory 118b1d4d-2511-4faf-b39e-468c40cc7248 hub.redsky Base Station
3/15/2021, 9:23:37 PM [Ring] Hidden accessory 4892c0d4-4774-4b2d-8e91-258092b903d8 security-keypad Entryway Keypad
3/15/2021, 9:23:37 PM [myQ] myQ API: Successfully connected to the myQ API.
3/15/2021, 9:23:49 PM [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG08461EDAB7, gateway: GW23001CF84D).
3/15/2021, 9:23:49 PM [myQ] myQ API: Discovered device family gateway: Hub [Chamberlain Smart Garage Hub] (serial number: GW23001CF84D).
3/15/2021, 9:23:49 PM [myQ] Garage Door: Door position sensor detected. Enabling battery status support.

**Comment by zpeters90** [comment]
sorry, took a couple of tries at this. Let me know if there’s anything additional I can do here.
