### ISSUE TITLE
Add support for MSS560X

### ISSUE THREAD

**Issue by ruel27** [donavanbecker/homebridge-meross-cloud#16]
Hi,
is it possible add support for MSS560X please?

Thank you

**Comment by donavanbecker** [comment]
@ruel27  not sure if you have saw or not, I was able to publish version 1.0.1. This version only supports mss110 right now but I would like to get this Meross device supported also. I have changed the device discovery up a little and was wondering if you could install the latest version of homebridge-meross-cloud? login and turn on devicediscovery?

then you would reboot homebridge and grab the new logs that will be outputted from this device discovery and paste them here so I can see what kind of command I can send to this device. Thanks!
