### ISSUE TITLE
Add support for MSS210

### ISSUE THREAD

**Issue by Pilotsohn** [donavanbecker/homebridge-meross-cloud#24]
This is for a NON native homekit version of the MSS210 Smart Plug.

Here is the discovery;:

{"uuid":"2011055687001551803748e1e93a5997","onlineStatus":1,"devName":"Steckdose 2","devIconId":"device024","bindTime":1612903159,"deviceType":"mss210","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"6.1.8","hdwareVersion":"6.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu-alter.meross.com"}

**Comment by donavanbecker** [comment]
@Pilotsohn not sure if you have saw or not, I was able to publish version 1.0.1. This version only supports mss110 right now but I would like to get this Meross device supported also. I have changed the device discovery up a little and was wondering if you could install the latest version of homebridge-meross-cloud? login and turn on devicediscovery?

then you would reboot homebridge and grab the new logs that will be outputted from this device discovery and paste them here so I can see what kind of command I can send to this device. Thanks!

**Comment by Pilotsohn** [comment]
Of course @donavanbecker: 

All-Data: {"all":{"system":{"hardware":{"type":"mss210","subType":"us","version":"6.0.0","chipType":"rtl8710cf","uuid":"2011055687001551803748e1e93a5997","macAddress":"48:e1:e9:3a:59:97"},"firmware":{"version":"6.1.8","compileTime":"2020/07/03-11:01:20","wifiMac":"3c:a6:2f:5c:e4:bf","innerIp":"192.168.178.78","server":"mqtt.meross.com","port":443,"userId":1173642},"time":{"timestamp":1614364614,"timezone":"Europe/Berlin","timeRule":[[1603587600,3600,0],[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":1613829026}],"triggerx":[],"timerx":[]}}}

**Comment by Pilotsohn** [comment]
Is that the information you needed?

**Comment by donavanbecker** [comment]
@Pilotsohn Yes!

**Comment by donavanbecker** [comment]
@Pilotsohn I have pushed out a beta for mss210, can you give it a try?

if you can install the latest beta:

Beta: `1.0.2-beta.5`

It is displaying as a outlet.

**Comment by Pilotsohn** [comment]
@donavanbecker 

Great, it works!

**Comment by donavanbecker** [comment]
v1.1.0 is released.
