### ISSUE TITLE
Device Type: msxh0 and mss425f are not supported. Do you think it can be ?

### ISSUE THREAD

**Issue by VilliX3S** [donavanbecker/homebridge-meross-cloud#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VilliX3S** [comment]
These 2 devises are not suppored : 
mss425f is a smart wifi surge protector (https://www.meross.com/product/19/article/)
msxh0 smart wifi humidifier (https://www.meross.com/product/47/article/)
Do you think you can make them supported ?
Thanks,
William

**Comment by donavanbecker** [comment]
@VilliX3S Please fill out the issue template correctly.
