### ISSUE TITLE
Add support for MSS110-2

### ISSUE THREAD

**Issue by gileswells** [donavanbecker/homebridge-meross-cloud#8]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add support for MSS110-2 devices

**Describe alternatives you've considered**

I looked at the codebase of `homebridge-meross` and it's clear that any attempts that I'd make to try and assist with implementing this device would end badly. Sorry.

**Additional context**

It looks like MSS110-1 might use the same interface based on the `homebridge-meross` plugin code so might work to add both device models at once.

**Comment by donavanbecker** [comment]
just release `v1.0.0` can you give it a try?

**Comment by gileswells** [comment]
@donavanbecker Literally just saw that and was like "Ooooh MSS110 is the first to be added? Nice." Actually I've been working through the update for the last hour or so and so far it's touchy but it's functional.

Was there a reason for adding mss110 to the end of all device names? Personally, if that's intentional and there isn't some larger rationale behind it, I'd prefer that not be included or at least allow a setting to opt into that.
Also it appears that Device Discovery was causing a reboot loop. Disabling device discovery brought things back online. I'm going to make a new issue for that and provide logs.

**Comment by donavanbecker** [comment]
That's one of the models I have  available to me and easiest to implement once I got things working right.

Adding the device type is something I have always just did to my plugins. I could remove it but then you would have to reset up everything again.

**Comment by gileswells** [comment]
Currently your Meross plugin is in a state of flux and I totally get that and embrace it. I'm not worried about breaking changes now since it'll help long term for all users. 

I love the idea of having a single login saved and from that we as users gain access to all the devices with very little effort. The overhead and slightly delayed response times that comes from having to connect through the cloud service for all requests instead of hitting the devices directly over the local network is unfortunately but well worth not having to go through the process of sniffing the traffic and setting up the signing manually so thank you for that.

Onto the topic of suffixes, I'd personally prefer to not have them (or at least have an option to toggle them). While it makes sense if you're always needing to know what each is without having to think about it, for me and more specifically the members of my family they don't care to see how the sausage is made.
